// Attribute each JS chunk's bytes to source packages via its sourcemap (sourcesContent length approximation using mappings).
import { readFileSync, readdirSync } from 'node:fs'
const dir = new URL('./dist/assets/', import.meta.url).pathname
const files = readdirSync(dir).filter((f) => f.endsWith('.js'))
// decode VLQ mappings to attribute generated bytes to sources
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
const lut = {}; for (let i = 0; i < 64; i++) lut[B64[i]] = i
function decodeLine(str) {
  const segs = []; let i = 0
  while (i < str.length) {
    const seg = []
    while (i < str.length && str[i] !== ',') {
      let v = 0, shift = 0, c
      do { c = lut[str[i++]]; v += (c & 31) << shift; shift += 5 } while (c & 32)
      seg.push(v & 1 ? -(v >>> 1) : v >>> 1)
    }
    i++; segs.push(seg)
  }
  return segs
}
for (const f of files) {
  const code = readFileSync(dir + f, 'utf8')
  let map
  try { map = JSON.parse(readFileSync(dir + f + '.map', 'utf8')) } catch { console.log(f, code.length, '(no map)'); continue }
  const lines = code.split('\n')
  const bySrc = new Map()
  let src = 0
  const mlines = map.mappings.split(';')
  for (let li = 0; li < mlines.length; li++) {
    const segs = mlines[li] ? decodeLine(mlines[li]) : []
    let col = 0
    const lineLen = (lines[li] ?? '').length
    const pts = []
    for (const s of segs) { col += s[0]; if (s.length > 1) { src += s[1]; pts.push([col, src]) } else pts.push([col, -1]) ; if (s.length>1){ /* skip rest */ } }
    // note: we ignore original line/col deltas except source index; need to still accumulate them? source idx delta only matters
    for (let k = 0; k < pts.length; k++) {
      const end = k + 1 < pts.length ? pts[k + 1][0] : lineLen
      const s = pts[k][1] < 0 ? '(none)' : map.sources[pts[k][1]]
      bySrc.set(s, (bySrc.get(s) ?? 0) + (end - pts[k][0]))
    }
  }
  const byPkg = new Map()
  for (const [s, n] of bySrc) {
    let key = s
    const m = /node_modules\/((?:@[^/]+\/)?[^/]+)/.exec(s)
    if (m) key = m[1]
    else if (s.includes('/src/')) key = 'src/' + s.split('/src/')[1].split('/').slice(0, 2).join('/')
    byPkg.set(key, (byPkg.get(key) ?? 0) + n)
  }
  const top = [...byPkg].sort((a, b) => b[1] - a[1]).slice(0, 14)
  console.log(`\n== ${f} ${(code.length / 1024).toFixed(1)} KiB`)
  for (const [k, n] of top) console.log(`  ${(n / 1024).toFixed(1).padStart(7)} KiB  ${k}`)
}
