// Snapshot of real Deezer playlist metadata for the lobby lab's offline mock catalog.
// Generated by scripts/lobby/fetch-mock.mjs — dev only.
import type { PlaylistRef } from '../../game/types'

export const MOCK_FEATURED: PlaylistRef[] = [
  {
    "id": 1116187241,
    "title": "Top Italy",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/99a09b06bcabba31bafbe095740085c4/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Deezer Charts"
  },
  {
    "id": 3155776842,
    "title": "Top Worldwide",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/0b92c2f9e94a1a3650f0de769c4fc07c/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Deezer Charts"
  },
  {
    "id": 579513551,
    "title": "Top Hits Italy 2026🎵 Hit del momento 🏖️ Estate 202",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/0036a7a7f0f8fe068c16d809cefb88c5/500x500-000000-80-0-0.jpg",
    "nbTracks": 291,
    "creator": "Filtr Italy"
  },
  {
    "id": 1363560485,
    "title": "Deezer Hits",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/3665881261eac64d90b58e8d8e0cc2c5/500x500-000000-80-0-0.jpg",
    "nbTracks": 50,
    "creator": "Alexandre - Pop & Hits Editor"
  },
  {
    "id": 4403076402,
    "title": "TikTok Hits World",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/5e3ba5756fc176475084503d8e12a397/500x500-000000-80-0-0.jpg",
    "nbTracks": 80,
    "creator": "Alexandre - Pop & Hits Editor"
  },
  {
    "id": 248297032,
    "title": "00s Hits",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/3e4cdc7e18c4ac1163bc7247f151731c/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Laeti - Deezer Pop Editor"
  },
  {
    "id": 878989033,
    "title": "90s Hits",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/2a49b51da3274d054f112cf06de50ffe/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Laeti - Deezer Pop Editor"
  },
  {
    "id": 867825522,
    "title": "80s Hits",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/9103f288c270025230263354f24bfd0d/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Laeti - Deezer Pop Editor"
  },
  {
    "id": 8282573142,
    "title": "10s Pop",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/a2c4a523d4054a2ddb04856f0f31282b/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Laeti - Deezer Pop Editor"
  },
  {
    "id": 1470022445,
    "title": "70s Hits",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/a6c90564396ad359fd080095d10f0bae/500x500-000000-80-0-0.jpg",
    "nbTracks": 70,
    "creator": "Laeti - Deezer Pop Editor"
  },
  {
    "id": 1306931615,
    "title": "Rock Essentials",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/e17f63541e66d8f110ae90207b6c6007/500x500-000000-80-0-0.jpg",
    "nbTracks": 100,
    "creator": "Rod - Deezer Rock Editor"
  },
  {
    "id": 12797956601,
    "title": "Italo Hits: Best of Italia 🍝🇮🇹",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/38d228ed9f279e4c0aa8896792b4d5e8/500x500-000000-80-0-0.jpg",
    "nbTracks": 69,
    "creator": "Filtr Germany"
  },
  {
    "id": 4562471864,
    "title": "Musica Italiana 🇮🇹 Best Of Italo Hits & Classics",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/fa9aeb48c1997f42e0ab8c2114c4fb89/500x500-000000-80-0-0.jpg",
    "nbTracks": 79,
    "creator": "Digster Austria"
  },
  {
    "id": 1931998962,
    "title": "Cantautori  Italiani",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/e310376de8a4ddb98bfc911996de8b35/500x500-000000-80-0-0.jpg",
    "nbTracks": 74,
    "creator": "Digster Italy"
  },
  {
    "id": 822101931,
    "title": "Pop Italiano 2026",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/13d0adbadb300336e08b9ac58608e9e3/500x500-000000-80-0-0.jpg",
    "nbTracks": 189,
    "creator": "Filtr Italy"
  },
  {
    "id": 1303152955,
    "title": "Rap Italiano Game Over",
    "picture": "https://cdn-images.dzcdn.net/images/playlist/4b41d65b95507fb9356d49d660049ffb/500x500-000000-80-0-0.jpg",
    "nbTracks": 59,
    "creator": "Digster Italy"
  }
]

export const MOCK_SEARCHES: Record<string, PlaylistRef[]> = {
  "rap italiano": [
    {
      "id": 1303152955,
      "title": "Rap Italiano Game Over",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/4b41d65b95507fb9356d49d660049ffb/500x500-000000-80-0-0.jpg",
      "nbTracks": 59,
      "creator": "Digster Italy"
    },
    {
      "id": 11395137964,
      "title": "🦉musica italiana rap trap che mi piace tanto",
      "picture": "https://cdn-images.dzcdn.net/images/cover/88e5e8f32f0c449c01e32646a78866ce-d41d8cd98f00b204e9800998ecf8427e-228c3519b713dcc128065dfedd7e4d19-6e68862906c8f3f400e69e8907f2b65f/500x500-000000-80-0-0.jpg",
      "nbTracks": 251,
      "creator": "Francesca"
    },
    {
      "id": 4761913924,
      "title": "Rap/trap italiano",
      "picture": "https://cdn-images.dzcdn.net/images/cover/d2abdc3e3872c1db15776dff686d2320-287acec4b16076d83ce9430290a6c385-1fe8e139d51788cc0291755386a79d66-edba6dda9303cdf72d32e0c443c49759/500x500-000000-80-0-0.jpg",
      "nbTracks": 105,
      "creator": "camilla"
    },
    {
      "id": 15426416061,
      "title": "Rap Italiano Old school Style - Anni 80 90 ... by ",
      "picture": "https://cdn-images.dzcdn.net/images/cover/30a849663007346666766df1c45093d5-722a771cf8ece8ee08cc58e5df42dda7-b9c0574d78d47e7d71d15f3d69c05e28-6d6228a9622663078537b8506c1d6648/500x500-000000-80-0-0.jpg",
      "nbTracks": 254,
      "creator": "Fabio"
    },
    {
      "id": 15201163963,
      "title": "Rap Italiano",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/77d13a08bd347251ecce33b84bd1fced/500x500-000000-80-0-0.jpg",
      "nbTracks": 26,
      "creator": "cpa"
    },
    {
      "id": 4464206844,
      "title": "Rap Italiano",
      "picture": "https://cdn-images.dzcdn.net/images/cover/115ea516a86136c5d61ae20aa6bf8f9f-45e764fc4af6071ad46c41a574d05087-d473af0b0d1e0ddcf974120eb7cc0104-7c379aa4e14a3e72eb1235ca0166d2c9/500x500-000000-80-0-0.jpg",
      "nbTracks": 213,
      "creator": "Marco Tempesta"
    },
    {
      "id": 14860732903,
      "title": "RAP UNDERGROUND ITALIANO OLD SCHOOL",
      "picture": "https://cdn-images.dzcdn.net/images/cover/d817f86dab445250dba1202bbabd732f-7abe11f646c4fba50e92e46cf86be149-d41d8cd98f00b204e9800998ecf8427e-273091cd50b5f112a98e6fa9082dad35/500x500-000000-80-0-0.jpg",
      "nbTracks": 338,
      "creator": "delfra"
    },
    {
      "id": 13070456203,
      "title": "Rap italiano ",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/9ce2b945ee260c16499d7db5291eb513/500x500-000000-80-0-0.jpg",
      "nbTracks": 277,
      "creator": "Qqualobbutu"
    },
    {
      "id": 153939681,
      "title": "Rap italiano ",
      "picture": "https://cdn-images.dzcdn.net/images/cover/7fdc82bd0ecaa9368017489c2d7482b1-60d02c7fa226dbf4bb17c85f9d7b322f-35611b65853b80ec810abbe9e53cd04e-87da49d75e7449d7b14bd0e9d3dbcbff/500x500-000000-80-0-0.jpg",
      "nbTracks": 147,
      "creator": "jmn55"
    },
    {
      "id": 14087850241,
      "title": "Il Rap Italiano",
      "picture": "https://cdn-images.dzcdn.net/images/cover/c63f07ace2863b051cc3a96274a18c20-a878984064220627b8132c5da74f64f9-abaa8008a44cd473e8435930a9254651-228c3519b713dcc128065dfedd7e4d19/500x500-000000-80-0-0.jpg",
      "nbTracks": 183,
      "creator": "john"
    },
    {
      "id": 13636595881,
      "title": "All Time Italian Rap",
      "picture": "https://cdn-images.dzcdn.net/images/cover/7430c11e7c5904baa3499979effc6dc3-c474668194bc8e80c39e4ab9c3641885-0a5f8dd740dfcc5c9fcb099ececcb833-228c3519b713dcc128065dfedd7e4d19/500x500-000000-80-0-0.jpg",
      "nbTracks": 116,
      "creator": "fabio.onofrih"
    },
    {
      "id": 14291089761,
      "title": "rap italiano",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/30eb61406543108e8642809c55e0d5a3/500x500-000000-80-0-0.jpg",
      "nbTracks": 20,
      "creator": "Francesco Ska Orrù"
    },
    {
      "id": 15425676141,
      "title": "Rap Italiano 🇮🇹 Trap 2026",
      "picture": "https://cdn-images.dzcdn.net/images/cover/277c5edad6dc3c45d7043776fc3cd3fe-b05f77f2f32b2f3b610f1502a3c29b3d-3ef91d24649be6698d62654bb9ea0855-f146c30ff4d4d676417038d5cc6ebdeb/500x500-000000-80-0-0.jpg",
      "nbTracks": 61,
      "creator": "NONO"
    },
    {
      "id": 14537148123,
      "title": "RAP UNDERGROUND ITALIANO",
      "picture": "https://cdn-images.dzcdn.net/images/cover/bb8d40cd49a39e6a0435c19e67cd6586-01505c262134cf5caeb610d79b2300f3-75c79baba9d3078b20659d5d53b567bb-7fdc82bd0ecaa9368017489c2d7482b1/500x500-000000-80-0-0.jpg",
      "nbTracks": 138,
      "creator": "mariouch"
    },
    {
      "id": 4234471622,
      "title": "sad italian rap.",
      "picture": "https://cdn-images.dzcdn.net/images/cover/d5eefa471b4636ada939c01223ff184b-fde9fab0eec074ad9ab2bc436166df31-aa042281b362427bc328df0645447d00-94f2b74618646d0d8d55a869f7c232f1/500x500-000000-80-0-0.jpg",
      "nbTracks": 31,
      "creator": "Francesco Cerqua"
    },
    {
      "id": 5133214324,
      "title": "Rap Italiano",
      "picture": "https://cdn-images.dzcdn.net/images/cover/9be2c8127cc6b731d1710e09f08e91df-d3d8fb040b07061182d11c22df8f2261-228c3519b713dcc128065dfedd7e4d19-764421c04861410c7f5ac652efce07bc/500x500-000000-80-0-0.jpg",
      "nbTracks": 157,
      "creator": "Stefano"
    }
  ],
  "80s hits": [
    {
      "id": 8512471762,
      "title": "80s Pop",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/377a616be06417dda8097b644a601359/500x500-000000-80-0-0.jpg",
      "nbTracks": 100,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 1913763402,
      "title": "80s Party Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/a7af848d1d99f8a5dadab161396e7932/500x500-000000-80-0-0.jpg",
      "nbTracks": 80,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 867825522,
      "title": "80s Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/9103f288c270025230263354f24bfd0d/500x500-000000-80-0-0.jpg",
      "nbTracks": 100,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 1276784581,
      "title": "80s Alternative",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/762fffcf17ba2f04acb16991522074e2/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Georges - Deezer Alternative Editor"
    },
    {
      "id": 8403360702,
      "title": "80s Ballads",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/436244c6179c0508b4250a5f98731a46/500x500-000000-80-0-0.jpg",
      "nbTracks": 80,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 8974688542,
      "title": "80s Club Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/049349728c4a59b0c64a140de5080c30/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Laeti - Deezer Dance & EDM Editor"
    },
    {
      "id": 1413309725,
      "title": "80s Pop Rock",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/ff411c2e1f8aaa6d883a7d3eb53093b8/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 1036183001,
      "title": "Pop Essentials",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/97be282b23f264f4586ef823cf513bf6/500x500-000000-80-0-0.jpg",
      "nbTracks": 80,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 7365666824,
      "title": "80s Soul",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/f93fe21456b76d761364294ada2f2422/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Yannick - Soul & Funk Deezer Editor"
    },
    {
      "id": 8951609622,
      "title": "70s & 80s Acoustic Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/16930388f1a5c4c63dd0a88ebb4c2b12/500x500-000000-80-0-0.jpg",
      "nbTracks": 40,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 10701318182,
      "title": "Top Hits 1983",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/842385aa4be18b80b4ee420dd0e4c168/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Deezer Best Of"
    },
    {
      "id": 6122724024,
      "title": "80s Summer Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/3986a822e002e758700e559c3709ea6a/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 10698676702,
      "title": "Top Hits 1985",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/b1ba28ac3f55881db3d2c8d49263c6bd/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Deezer Best Of"
    },
    {
      "id": 8873745702,
      "title": "80s Happy Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/4218d671b3ef0709b98e2d739c00e8ec/500x500-000000-80-0-0.jpg",
      "nbTracks": 80,
      "creator": "Laeti - Deezer Pop Editor"
    },
    {
      "id": 11798808421,
      "title": "80s HITS - 100 Greatest Songs of the 1980s",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/74b0f3a3cef51fc6ccf5b20e4d028fc5/500x500-000000-80-0-0.jpg",
      "nbTracks": 100,
      "creator": "Topsify"
    },
    {
      "id": 1026896991,
      "title": "80s Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/f6a0ceff5fc4cd6646f9189ac8a800e9/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "HITS"
    }
  ],
  "rock classics": [
    {
      "id": 1437011185,
      "title": "60s Rock",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/d5ce161472af8056ee2527eeed384f8d/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 1306931615,
      "title": "Rock Essentials",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/e17f63541e66d8f110ae90207b6c6007/500x500-000000-80-0-0.jpg",
      "nbTracks": 100,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 1419215845,
      "title": "2000s Rock",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/739dc932dcf31874c90b9fd9baf41eba/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 3126664682,
      "title": "Rock Road Trip",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/8f0c45b8a88e34abced62eddb73ea23a/500x500-000000-80-0-0.jpg",
      "nbTracks": 80,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 2865616602,
      "title": "Women of Rock",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/e58758c30f20ce5c788a58f6d7668f88/500x500-000000-80-0-0.jpg",
      "nbTracks": 80,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 1057779131,
      "title": "2010s Rock",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/f3fd225cc6753703afac9c0a2d613584/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 11242423484,
      "title": "Rock Super Hits",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/c40310d88ae4c8231250cbceaa06e59a/500x500-000000-80-0-0.jpg",
      "nbTracks": 100,
      "creator": "Yannick - Deezer Deutschland Editor"
    },
    {
      "id": 1393810385,
      "title": "Heavy Party",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/ce6786ecd9164b05371150da12570c31/500x500-000000-80-0-0.jpg",
      "nbTracks": 50,
      "creator": "Rod - Deezer Metal Editor"
    },
    {
      "id": 13693489781,
      "title": "2020s Rock",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/01dd09264b399845b58418949ae33a8e/500x500-000000-80-0-0.jpg",
      "nbTracks": 99,
      "creator": "Rod - Deezer Rock Editor"
    },
    {
      "id": 12334997451,
      "title": "Rock Antigo | Rock Clássico 70 80 90",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/9df1b4b6ce92bb5190eadb6951b98dc8/500x500-000000-80-0-0.jpg",
      "nbTracks": 108,
      "creator": "Filtr Music Brasil"
    },
    {
      "id": 12051974211,
      "title": "GTA Liberty Rock Radio",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/2866a569021a6c857fd11142f5311249/500x500-000000-80-0-0.jpg",
      "nbTracks": 36,
      "creator": "Camojada - Deezer Gaming Editor"
    },
    {
      "id": 2559083668,
      "title": "Clásicos del rock en español",
      "picture": "https://cdn-images.dzcdn.net/images/cover/792bf9c60ea9f8584851719be3e2c52f-7627401bacd438bebf1831625d51335f-4b4105fe7628d60e63340efb7def78f1-7327f13efbffa6f5b802d869cd4331af/500x500-000000-80-0-0.jpg",
      "nbTracks": 69,
      "creator": "Santiago.García.Ortiz"
    },
    {
      "id": 9268293682,
      "title": "Clássicos do Rock Nacional",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/d4408fdaea25eed678c569618e68aac7/500x500-000000-80-0-0.jpg",
      "nbTracks": 51,
      "creator": "Editores Deezer Brasil"
    },
    {
      "id": 3974574342,
      "title": "Rock Classics",
      "picture": "https://cdn-images.dzcdn.net/images/cover/42116e109cccb87cd2b8bc4a401d88a5-b4ec4a1a920d792dd7d8d15dc29f0a39-641c709b0634c089d9ba36f430b765bb-44df4f6fb2534768f4924365c103d0f7/500x500-000000-80-0-0.jpg",
      "nbTracks": 305,
      "creator": "Ernst Meidel"
    },
    {
      "id": 11218552684,
      "title": "Yacht Rock • 70s & 80s Soft Rock Classics",
      "picture": "https://cdn-images.dzcdn.net/images/playlist/789a9cb80c1770efaf4ce55d93891826/500x500-000000-80-0-0.jpg",
      "nbTracks": 108,
      "creator": "Topsify"
    },
    {
      "id": 7907252202,
      "title": "Rock Classics",
      "picture": "https://cdn-images.dzcdn.net/images/cover/bb609cb3866b695e21e9c3125de75d2b-41041b14873956eff0459c8ea2c296a8-be2466b2d06a94d0e7d8350c4e7c4dc0-88e63fb246cb108a8fe6da4986a47a9b/500x500-000000-80-0-0.jpg",
      "nbTracks": 118,
      "creator": "Georg Fuchsbichler"
    }
  ]
}
