import { chromium } from 'playwright'
const OUT = new URL('./shots/', import.meta.url).pathname
const browser = await chromium.launch({ channel: 'chrome' })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: process.argv[2] === 'reduced' ? 'reduce' : 'no-preference' })
const page = await ctx.newPage()
page.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await page.goto('http://localhost:5202/lab/board.html?n=12&audio=synth&ui=0&marks=' + (process.argv[2] === 'reduced' ? '1' : '0'))
await page.waitForFunction(() => window.__lab && window.__lab.ready())
await page.waitForTimeout(400)
await page.keyboard.press('Tab')
await page.keyboard.press('Tab')
await page.waitForTimeout(200)
await page.screenshot({ path: `${OUT}k-focus${process.argv[2] ?? ''}.png`, clip: { x: 80, y: 60, width: 700, height: 330 } })
await page.keyboard.press('Space')
await page.waitForTimeout(250)
await page.keyboard.press('ArrowRight')
await page.waitForTimeout(350)
await page.screenshot({ path: `${OUT}k-drag${process.argv[2] ?? ''}.png`, clip: { x: 80, y: 60, width: 1000, height: 330 } })
const live = await page.evaluate(() => [...document.querySelectorAll('[role=status], [aria-live]')].map((e) => e.textContent).filter(Boolean))
console.log('live regions:', live)
const instr = await page.evaluate(() => [...document.querySelectorAll('[id^=DndDescribedBy]')].map((e) => e.textContent))
console.log('instructions:', instr)
const label = await page.evaluate(() => { const e = document.activeElement; return [e.getAttribute('aria-label'), e.getAttribute('aria-roledescription'), e.getAttribute('role')] })
console.log('focused:', label)
await page.keyboard.press('Space')
await page.waitForTimeout(400)
console.log('live after drop:', await page.evaluate(() => [...document.querySelectorAll('[aria-live]')].map((e) => e.textContent).filter(Boolean)))
await browser.close()
