// Board against the REAL audio engine + Deezer preview.
import { chromium } from 'playwright'
const OUT = new URL('./shots/', import.meta.url).pathname
const browser = await chromium.launch({ channel: 'chrome', args: ['--autoplay-policy=no-user-gesture-required'] })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const page = await ctx.newPage()
page.on('pageerror', (e) => console.log('PAGEERROR', e.message))
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('404')) console.log('CONSOLE', m.text()) })
await page.goto('http://localhost:5202/lab/board.html?n=8&ui=0&engine=real')
await page.waitForFunction(() => window.__lab && window.__lab.ready(), null, { timeout: 25000 })
console.log('engine is real:', await page.evaluate(() => typeof window.__lab.engine.inject === 'undefined'))
await page.locator('.sb-item[data-pos="0"]').click()
await page.waitForTimeout(700)
console.log('after click', JSON.stringify(await page.evaluate(() => [window.__lab.engine.getState(), window.__lab.engine.getPosition()])))
await page.screenshot({ path: `${OUT}real-block.png` })
await page.keyboard.press('Space')
await page.waitForTimeout(2600)
console.log('after space', JSON.stringify(await page.evaluate(() => [window.__lab.engine.getState(), window.__lab.engine.getPosition()])))
await page.screenshot({ path: `${OUT}real-playall.png` })
// reorder during playback: move the block at position 3 to position 1 (upcoming positions change)
const box = async (p) => page.locator(`.sb-item[data-pos="${p}"]`).boundingBox()
const a = await box(3), b = await box(1)
await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2)
await page.mouse.down()
for (let i = 1; i <= 12; i++) { await page.mouse.move(a.x + a.width / 2 + ((b.x - a.x) * i) / 12, a.y + a.height / 2 + ((b.y - a.y) * i) / 12); await page.waitForTimeout(16) }
await page.mouse.up()
await page.waitForTimeout(3800)
const lit = await page.$$eval('.sb-block[data-playing]', (els) => els.map((e) => e.closest('.sb-item').dataset.pos))
console.log('state after reorder', JSON.stringify(await page.evaluate(() => window.__lab.engine.getState())), 'lit pos', lit)
await page.keyboard.press('Space')
await page.waitForTimeout(300)
console.log('stopped', JSON.stringify(await page.evaluate(() => window.__lab.engine.getState())))
await browser.close()
