// Snapshot real Deezer playlist metadata into src/dev/lobby/mockData.ts (dev-only mock catalog).
import { writeFileSync } from 'node:fs'
const ids = [1116187241, 3155776842, 579513551, 1363560485, 4403076402, 248297032, 878989033, 867825522, 8282573142, 1470022445, 1306931615, 12797956601, 4562471864, 1931998962, 822101931, 1303152955]
const ref = (p) => ({ id: p.id, title: p.title, picture: p.picture_big, nbTracks: p.nb_tracks, ...(p.user?.name || p.creator?.name ? { creator: p.user?.name || p.creator?.name } : {}) })
const featured = []
for (const id of ids) {
  const r = await fetch(`https://api.deezer.com/playlist/${id}?limit=1`).then((r) => r.json())
  if (r.id) featured.push(ref(r))
}
const searches = {}
for (const q of ['rap italiano', '80s hits', 'rock classics']) {
  const r = await fetch(`https://api.deezer.com/search/playlist?q=${encodeURIComponent(q)}&limit=16`).then((r) => r.json())
  searches[q] = (r.data ?? []).filter((p) => p.nb_tracks >= 10).map(ref)
}
const out = `// Snapshot of real Deezer playlist metadata for the lobby lab's offline mock catalog.
// Generated by scripts/lobby/fetch-mock.mjs — dev only.
import type { PlaylistRef } from '../../game/types'

export const MOCK_FEATURED: PlaylistRef[] = ${JSON.stringify(featured, null, 2)}

export const MOCK_SEARCHES: Record<string, PlaylistRef[]> = ${JSON.stringify(searches, null, 2)}
`
writeFileSync(new URL('../../src/dev/lobby/mockData.ts', import.meta.url), out)
console.log(featured.length, Object.values(searches).map((s) => s.length))
