// Pseudo-Italian: the Italian catalog with accented, ~40% longer text, to find layouts that
// can't take a longer translation before the translations exist.
//
//   node tests/e2e/pseudo/generate.mjs            → writes tests/e2e/pseudo/it-pseudo.generated.js
//   node tests/e2e/pseudo/generate.mjs --print    → prints a few samples
//
// The dev server of ./vite.config.ts runs this itself (and again whenever the Italian
// catalog changes), so the generated file never needs to be committed.
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { loadCatalog, messages, pseudoCatalog } from './catalogs.mjs'

export const PSEUDO_FILE = fileURLToPath(new URL('./it-pseudo.generated.js', import.meta.url))

/** Build the pseudo catalog from the current Italian files and write it as an ES module. */
export async function generatePseudo({ fresh = false, file = PSEUDO_FILE } = {}) {
  const it = await loadCatalog('it', { fresh })
  const pseudo = pseudoCatalog(it)
  const header =
    '// GENERATED by tests/e2e/pseudo/generate.mjs from src/i18n/locales/it — do not edit.\n' +
    '// Pseudo-Italian: accented, ~40% longer text; {params}, <tags>, plural keys, lists and data kept.\n'
  writeFileSync(file, `${header}export default ${JSON.stringify(pseudo, null, 2)}\n`)
  return { it, pseudo, file }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { it, pseudo, file } = await generatePseudo()
  const all = messages(it)
  console.log(`wrote ${file} (${all.length} messages)`)
  if (process.argv.includes('--print')) {
    const pm = new Map(messages(pseudo).map((m) => [m.key, m.forms]))
    for (const { key, forms } of all.filter((_, i) => i % 25 === 0)) console.log(`${key}\n  ${forms[0]}\n  ${pm.get(key)?.[0]}`)
  }
}
