import { chromium, webkit, devices } from 'playwright'
const BASE = 'http://127.0.0.1:5302'
const b = await chromium.launch({ channel: 'chrome', args: ['--autoplay-policy=no-user-gesture-required'] })
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
const p = await ctx.newPage()
const cdp = await ctx.newCDPSession(p)
try {
  const r = await cdp.send('Emulation.setSafeAreaInsetsOverride', { insets: { top: 47, bottom: 34, left: 0, right: 0 } })
  console.log('safe area override ok', r)
} catch (e) { console.log('safe area override failed', e.message) }
await p.goto(BASE + '/lab/shell.html?real=1&panel=0')
await p.waitForTimeout(1500)
console.log(await p.evaluate(() => { const d = document.createElement('div'); d.style.cssText='position:fixed;top:env(safe-area-inset-top);left:0'; document.body.appendChild(d); const t = d.getBoundingClientRect().top; d.remove(); return { t, hasShell: !!window.__shell } }))
await p.screenshot({ path: '/Users/tom/Developer/vibes/oooo/scripts/qa-mobile/shots/probe-chrome-home.png' })
await b.close()
const w = await webkit.launch()
const wctx = await w.newContext({ ...devices['iPhone 14'] })
const wp = await wctx.newPage()
wp.on('console', (m) => m.type() === 'error' && console.log('wk console', m.text().slice(0, 200)))
wp.on('pageerror', (e) => console.log('wk pageerror', e.message))
await wp.goto(BASE + '/')
await wp.waitForTimeout(3000)
console.log(await wp.evaluate(() => ({ ua: navigator.userAgent, w: innerWidth, h: innerHeight, gl2: !!document.createElement('canvas').getContext('webgl2'), AC: typeof AudioContext, screen: document.querySelector('[data-screen-frame]')?.getAttribute('data-screen') })))
await wp.screenshot({ path: '/Users/tom/Developer/vibes/oooo/scripts/qa-mobile/shots/probe-webkit-home.png' })
await w.close()
