import { launch, openPlayer, DESKTOP, createRoom, pickPlaylist, setSettings, startGame, waitPhase, boardReady, sleep, log, shot } from './lib.mjs'
const b = await launch()
const h = await openPlayer(b, 'Host', DESKTOP)
const g = await openPlayer(b, 'Sofi', { viewport: { width: 1280, height: 800 } })
const code = await createRoom(h)
const { joinByLink } = await import('./lib.mjs')
await joinByLink(g, code)
await pickPlaylist(h)
await setSettings(h, { rounds: 3, snippets: 6, roundTime: 60, finalTimer: 10 })
await startGame(h)
const inspect = (p) => p.evaluate(() => [...document.querySelectorAll('button')].filter((b) => /^\s*Conferma/i.test(b.textContent ?? '')).map((b) => {
  const r = b.getBoundingClientRect()
  const at = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2)
  return { text: b.textContent.trim(), disabled: b.disabled, inert: !!b.closest('[inert]'), w: r.width, h: r.height, x: r.x, y: r.y, hit: at === b || b.contains(at), hitEl: at ? at.tagName + '.' + (at.className?.baseVal ?? at.className ?? '').toString().slice(0, 80) : null, frame: b.closest('[data-screen-frame]')?.getAttribute('data-screen') }
}))
for (let r = 0; r < 2; r++) {
  await waitPhase(h, 'playing', r); await waitPhase(g, 'playing', r)
  await boardReady(g); await sleep(1800)
  log('round', r, 'guest buttons', JSON.stringify(await inspect(g)))
  log('round', r, 'host buttons', JSON.stringify(await inspect(h)))
  await shot(g, `dbg-r${r}`)
  await h.getByRole('button', { name: /^Conferma/ }).first().click({ timeout: 8000 }).then(() => log('host click ok')).catch((e) => log('host click FAIL', e.message.split('\n').slice(0, 12).join(' | ')))
  await sleep(1700)
  log('after first: guest buttons', JSON.stringify(await inspect(g)))
  const t = Date.now()
  await g.getByRole('button', { name: /^Conferma/ }).first().click({ timeout: 8000 }).then(() => log('guest click ok', Date.now() - t)).catch((e) => log('guest click FAIL', e.message.split('\n').slice(0, 30).join(' | ')))
  await waitPhase(h, 'reveal', r, 80000)
  await sleep(2000)
  await h.getByRole('button', { name: /Prossimo round/ }).first().click()
}
await b.close()
